title: Nick Lionakis's Personal site
author: Nick Lionakis
email: nick.lionakis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this site you will find useful information about me.

# social links
github_username:  NikosLion

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
